server:
  port: 9002
spring:
  application:
    name: tensquare-recruit #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.142.82:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 19971104
  jpa:
    database: MySQL
    show-sql: true
