server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.142.82:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 19971104
  jpa:
    database: mysql
    show-sql: true

