server:
  port: 13879
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aixiaoqie/tensquare.git
#          username: aixiaoqie
#          password: *19971104.ying

#  rabbitmq:
#    host: 192.168.217.136
#management: #暴露触发消息总线的地址
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh