server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.142.82:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: 19971104
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.120.200
  rabbitmq:
    host: 192.168.120.200