server:
  port: 6868
eureka:
  client:
    register-with-eureka: false #是否注册到eureka, 默认为true
    fetch-registry: false #是否获取注册信息，默认为true
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
