server: 
  port: 9012
spring: 
  application:  
    name: tensquare-web #指定服务名
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #跨域访问
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
    tensquare-qa:
      path: /problem/**
      serviceId: tensquare-qa
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend