server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.120.200:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 19971104
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast
    ttl: 3600000
